# Generated by Django 5.1.7 on 2025-05-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='path',
            new_name='file',
        ),
    ]
