# Generated by Django 5.1.7 on 2025-06-06 03:19

import media.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='file',
            field=models.ImageField(upload_to=media.utils.upload_to_images),
        ),
    ]
