# Generated by Django 5.1.7 on 2025-05-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeVersionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=256, null=True)),
                ('trade_union_membership_number', models.CharField(blank=True, max_length=255, null=True)),
                ('working_group_authentic_label', models.CharField(max_length=255, null=True)),
                ('trade_union_department_path', models.CharField(max_length=255, null=True)),
                ('trade_union_department_authentic_label', models.CharField(max_length=255, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_retired', models.BooleanField(default=False)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('academic_degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_versions', to='references.academicdegreemodel')),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_versions', to='references.educationlevelmodel')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_versions', to='employees.employeemodel')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_versions', to='references.gendermodel')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_versions', to='media.imagemodel')),
                ('working_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_versions', to='references.workinggroupmodel')),
            ],
            options={
                'db_table': 'employee_versions',
            },
        ),
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=128)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='employees.employeeversionmodel')),
            ],
            options={
                'db_table': 'emails',
            },
        ),
        migrations.CreateModel(
            name='EducationalInstitutionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('graduated_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_institutions', to='employees.employeeversionmodel')),
            ],
            options={
                'db_table': 'educational_institutions',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(max_length=512)),
                ('employee_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='employees.employeeversionmodel')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='BntuPositionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('bntu_department_authentic_label', models.CharField(max_length=255)),
                ('bntu_department_path', models.CharField(blank=True, max_length=255, null=True)),
                ('hired_at', models.DateTimeField(blank=True, null=True)),
                ('is_discharged', models.BooleanField(default=False)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('is_discharged_voluntarily', models.BooleanField(blank=True, null=True)),
                ('dischargement_comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bntu_positions', to='employees.employeeversionmodel')),
            ],
            options={
                'db_table': 'bntu_positions',
            },
        ),
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='employees.employeeversionmodel')),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='employees.employeeversionmodel')),
                ('phone_number_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_numbers', to='references.phonenumbertypemodel')),
            ],
            options={
                'db_table': 'phone_numbers',
            },
        ),
        migrations.CreateModel(
            name='RelativeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128)),
                ('birthdate', models.DateTimeField(null=True)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='employees.employeeversionmodel')),
                ('relative_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.relativetypemodel')),
            ],
            options={
                'db_table': 'relatives',
            },
        ),
        migrations.CreateModel(
            name='RewardModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='employees.employeeversionmodel')),
            ],
            options={
                'db_table': 'rewards',
            },
        ),
    ]
