# Generated by Django 5.1.7 on 2025-04-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeversionmodel',
            old_name='working_group_option',
            new_name='working_group',
        ),
        migrations.RenameField(
            model_name='employeeversionmodel',
            old_name='working_group_option_authentic_label',
            new_name='working_group_authentic_label',
        ),
    ]
