# Generated by Django 5.1.7 on 2025-06-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('references', '0003_exemptionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeversionmodel',
            name='exemptions',
            field=models.ManyToManyField(related_name='employee_versions', to='references.exemptionmodel'),
        ),
    ]
