# Generated by Django 5.1.7 on 2025-05-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeversionmodel',
            name='trade_union_membership_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
