# Generated by Django 5.1.7 on 2025-05-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeversionmodel_trade_union_membership_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeUnionPositionModel',
        ),
    ]
