# Generated by Django 5.1.7 on 2025-04-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_working_group_option_employeeversionmodel_working_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bntudepartmentmodel',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tradeuniondepartmentmodel',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
