# Generated by Django 5.1.7 on 2025-04-29 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_bntudepartmentmodel_label_and_more'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeversionmodel',
            name='academic_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_versions', to='references.academicdegreemodel'),
        ),
        migrations.AlterField(
            model_name='employeeversionmodel',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_versions', to='references.educationlevelmodel'),
        ),
        migrations.AlterField(
            model_name='employeeversionmodel',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_versions', to='references.gendermodel'),
        ),
        migrations.AlterField(
            model_name='phonenumbermodel',
            name='phone_number_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='references.phonenumbertypemodel'),
        ),
        migrations.AlterField(
            model_name='relativemodel',
            name='relative_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.relativetypemodel'),
        ),
        migrations.AlterField(
            model_name='employeeversionmodel',
            name='working_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_versions', to='references.workinggroupmodel'),
        ),
        migrations.DeleteModel(
            name='AcademicDegreeModel',
        ),
        migrations.DeleteModel(
            name='EducationLevelModel',
        ),
        migrations.DeleteModel(
            name='GenderModel',
        ),
        migrations.DeleteModel(
            name='PhoneNumberTypeModel',
        ),
        migrations.DeleteModel(
            name='RelativeTypeModel',
        ),
        migrations.DeleteModel(
            name='WorkingGroupModel',
        ),
    ]
