# Generated by Django 5.1.7 on 2025-04-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegreeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'academic_degrees',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationLevelModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'education_levels',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'genders',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'phone_number_types',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelativeTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'relative_types',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingGroupModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'working_group_options',
                'abstract': False,
            },
        ),
    ]
