# Generated by Django 5.1.7 on 2025-05-19 17:39

from django.db import migrations


def fill_initial_data(apps, schema_editor):
    GenderModel = apps.get_model("references", "GenderModel")
    EducationLevelModel = apps.get_model("references", "EducationLevelModel")
    AcademicDegreeModel = apps.get_model("references", "AcademicDegreeModel")
    PhoneNumberTypeModel = apps.get_model("references", "PhoneNumberTypeModel")
    RelativeTypeModel = apps.get_model("references", "RelativeTypeModel")

    GenderModel.objects.bulk_create(
        [
            GenderModel(id=0, label="Женский"),
            GenderModel(id=1, label="Мужской"),
        ]
    )

    EducationLevelModel.objects.bulk_create(
        [
            EducationLevelModel(id=0, label="Начальное"),
            EducationLevelModel(id=1, label="Основное"),
            EducationLevelModel(id=2, label="Среднее"),
            EducationLevelModel(id=3, label="Среднеe специальное"),
            EducationLevelModel(id=4, label="Профессиональноe техническое"),
            EducationLevelModel(id=5, label="Незаконченное высшее"),
            EducationLevelModel(id=6, label="Высшее"),
        ]
    )

    AcademicDegreeModel.objects.bulk_create(
        [
            AcademicDegreeModel(id=0, label="Кандидат наук"),
            AcademicDegreeModel(id=1, label="Доктор наук"),
        ]
    )

    PhoneNumberTypeModel.objects.bulk_create(
        [
            PhoneNumberTypeModel(id=0, label="Мобильный"),
            PhoneNumberTypeModel(id=1, label="Домашний"),
        ]
    )

    RelativeTypeModel.objects.bulk_create(
        [
            RelativeTypeModel(id=0, label="Ребёнок (родной)"),
            RelativeTypeModel(id=1, label="Ребёнок (опека)"),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(fill_initial_data),
    ]
