# Generated by Django 5.1.7 on 2025-06-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExemptionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'exemptions',
                'abstract': False,
            },
        ),
    ]
