# Generated by Django 5.1.7 on 2025-03-31 05:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'academic_degrees',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BntuDepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bntu_departments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationLevelModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'education_levels',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'genders',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'phone_number_types',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelativeTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'relative_types',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradeUnionDepartmentOptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'trade_union_department_options',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingGroupOptionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'working_group_options',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=256, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_retired', models.BooleanField(default=False)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('academic_degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.academicdegree')),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.educationlevelmodel')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.gendermodel')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=128)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='employees.employeemodel')),
            ],
            options={
                'db_table': 'emails',
            },
        ),
        migrations.CreateModel(
            name='EducationalInstitutionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('graduated_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_institutions', to='employees.employeemodel')),
            ],
            options={
                'db_table': 'educational_institutions',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(max_length=512)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='employees.employeemodel')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='BntuPositionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('hired_at', models.DateTimeField(blank=True, null=True)),
                ('is_discharged', models.BooleanField(default=False)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('is_discharged_voluntarily', models.BooleanField(blank=True, null=True)),
                ('dischargement_comment', models.TextField(blank=True, max_length=512, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bntu_positions', to='employees.bntudepartmentmodel')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bntu_positions', to='employees.employeemodel')),
            ],
            options={
                'db_table': 'bntu_positions',
            },
        ),
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='employees.employeemodel')),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='NameModel',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='employees.employeemodel')),
            ],
            options={
                'db_table': 'names',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='employees.employeemodel')),
                ('phone_number_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.phonenumbertypemodel')),
            ],
            options={
                'db_table': 'phone_numbers',
            },
        ),
        migrations.CreateModel(
            name='RelativeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128)),
                ('birthdate', models.DateTimeField(null=True)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='employees.employeemodel')),
                ('relative_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.relativetypemodel')),
            ],
            options={
                'db_table': 'relatives',
            },
        ),
        migrations.CreateModel(
            name='RewardModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='employees.employeemodel')),
            ],
            options={
                'db_table': 'rewards',
            },
        ),
        migrations.CreateModel(
            name='TradeUnionDepartmentModel',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_union_departments', to='employees.employeemodel')),
                ('trade_union_department_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_union_departments', to='employees.tradeuniondepartmentoptionmodel')),
            ],
            options={
                'db_table': 'trade_union_departments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradeUnionPositionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_union_positions', to='employees.employeemodel')),
            ],
            options={
                'db_table': 'trade_union_positions',
            },
        ),
        migrations.CreateModel(
            name='WorkingGroupModel',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_groups', to='employees.employeemodel')),
                ('working_group_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_groups', to='employees.workinggroupoptionmodel')),
            ],
            options={
                'db_table': 'working_groups',
                'abstract': False,
            },
        ),
    ]
