# Generated by Django 5.1.7 on 2025-03-30 17:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'academic_degrees',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BntuDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bntu_departments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'education_levels',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'genders',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'phone_number_types',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelativeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'relative_types',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradeUnionDepartmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'trade_union_department_options',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingGroupOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'working_group_options',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=256, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_retired', models.BooleanField(default=False)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('academic_degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.academicdegree')),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.educationlevel')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.gender')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=128)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='employees.employee')),
            ],
            options={
                'db_table': 'emails',
            },
        ),
        migrations.CreateModel(
            name='EducationalInstitution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('graduated_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_institutions', to='employees.employee')),
            ],
            options={
                'db_table': 'educational_institutions',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(max_length=512)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='employees.employee')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='BntuPosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('hired_at', models.DateTimeField(blank=True, null=True)),
                ('is_discharged', models.BooleanField(default=False)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('is_discharged_voluntarily', models.BooleanField(blank=True, null=True)),
                ('dischargement_comment', models.TextField(blank=True, max_length=512, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bntu_positions', to='employees.bntudepartment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bntu_positions', to='employees.employee')),
            ],
            options={
                'db_table': 'bntu_positions',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='employees.employee')),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='employees.employee')),
            ],
            options={
                'db_table': 'names',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='employees.employee')),
                ('phone_number_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.phonenumbertype')),
            ],
            options={
                'db_table': 'phone_numbers',
            },
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128)),
                ('birthdate', models.DateTimeField(null=True)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='employees.employee')),
                ('relative_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.relativetype')),
            ],
            options={
                'db_table': 'relatives',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='employees.employee')),
            ],
            options={
                'db_table': 'rewards',
            },
        ),
        migrations.CreateModel(
            name='TradeUnionDepartment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_union_departments', to='employees.employee')),
                ('trade_union_department_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_union_departments', to='employees.tradeuniondepartmentoption')),
            ],
            options={
                'db_table': 'trade_union_departments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradeUnionPosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_union_positions', to='employees.employee')),
            ],
            options={
                'db_table': 'trade_union_positions',
            },
        ),
        migrations.CreateModel(
            name='WorkingGroup',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_groups', to='employees.employee')),
                ('working_group_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_groups', to='employees.workinggroupoption')),
            ],
            options={
                'db_table': 'working_groups',
                'abstract': False,
            },
        ),
    ]
