# Generated by Django 5.1.7 on 2025-04-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bntupositionmodel',
            name='bntu_department_option',
        ),
        migrations.RemoveField(
            model_name='tradeuniondepartmentrecordmodel',
            name='trade_union_department_option',
        ),
        migrations.AddField(
            model_name='bntupositionmodel',
            name='bntu_department_option_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tradeuniondepartmentrecordmodel',
            name='trade_union_department_option_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
