# Generated by Django 5.1.7 on 2025-03-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='value',
        ),
        migrations.AddField(
            model_name='educationalinstitution',
            name='comment',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='educationalinstitution',
            name='graduated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
