# Generated by Django 5.1.7 on 2025-03-22 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_name_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BntuPositionName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='bntudepartment',
            old_name='working_positions',
            new_name='bntu_positions',
        ),
        migrations.RenameField(
            model_name='bntuposition',
            old_name='dischargedAt',
            new_name='discharged_at',
        ),
        migrations.RenameField(
            model_name='bntuposition',
            old_name='comment',
            new_name='dischargement_comment',
        ),
        migrations.RenameField(
            model_name='bntuposition',
            old_name='hiredAt',
            new_name='hired_at',
        ),
        migrations.RenameField(
            model_name='bntuposition',
            old_name='isDischarged',
            new_name='is_discharged',
        ),
        migrations.RenameField(
            model_name='bntuposition',
            old_name='isDischargedVoluntarily',
            new_name='is_discharged_voluntarily',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='value',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='academic_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.academicdegree'),
        ),
        migrations.AlterField(
            model_name='bntuposition',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='employees.bntupositionname'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.educationlevel'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.gender'),
        ),
    ]
