# Generated by Django 5.1.7 on 2025-03-22 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_academicdegree_bntupositionname_educationlevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelativeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='workinggroup',
            old_name='name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='type',
        ),
        migrations.RemoveField(
            model_name='relative',
            name='type',
        ),
        migrations.RemoveField(
            model_name='workinggroup',
            name='positions',
        ),
        migrations.AddField(
            model_name='tradeunionposition',
            name='working_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='employees.workinggroup'),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='employees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educational_institutions', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phone_number_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.phonenumbertype'),
        ),
        migrations.AddField(
            model_name='relative',
            name='relative_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.relativetype'),
        ),
    ]
