# Generated by Django 5.1.7 on 2025-03-22 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_phonenumbertype_relativetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='employees.employee'),
        ),
    ]
