from .trade_union_position_serializer import TradeUnionPositionSerializer
from .working_group_record_serializer import WorkingGroupRecordSerializer
from .trade_union_department_record_serializer import (
    TradeUnionDepartmentRecordSerializer,
)
